# Generated by Django 5.2.17 on 2026-09-05 23:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_india_defaults'),
        ('organization', '0002_branch_record_version_company_record_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_categories', to='organization.company')),
            ],
            options={
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('internal_code', models.CharField(max_length=40)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('part_number', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(max_length=500)),
                ('specification', models.TextField(blank=True)),
                ('warranty_months', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('reorder_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('alternates', models.ManyToManyField(blank=True, to='inventory.product')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='organization.company')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masters.unitofmeasure')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productcategory')),
            ],
            options={
                'ordering': ['company__name', 'description'],
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('bin_code', models.CharField(blank=True, max_length=40)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_locations', to='organization.warehouse')),
            ],
            options={
                'ordering': ['warehouse__name', 'bin_code'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('DAMAGED', 'Damaged'), ('REPAIR_HELD', 'Repair-held'), ('DEMO', 'Demo'), ('IN_TRANSIT', 'In-transit')], default='AVAILABLE', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.stocklocation')),
            ],
            options={
                'ordering': ['product__description', 'location__warehouse__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_number', models.CharField(max_length=80)),
                ('movement_type', models.CharField(choices=[('INWARD', 'Inward'), ('OUTWARD', 'Outward'), ('RESERVE', 'Reserve'), ('RELEASE_RESERVE', 'Release Reservation'), ('RETURN', 'Return'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment'), ('PANEL_CONSUMPTION', 'Panel Consumption'), ('SERVICE_CONSUMPTION', 'Service Consumption')], max_length=24)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('from_condition', models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('DAMAGED', 'Damaged'), ('REPAIR_HELD', 'Repair-held'), ('DEMO', 'Demo'), ('IN_TRANSIT', 'In-transit')], max_length=20)),
                ('to_condition', models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('DAMAGED', 'Damaged'), ('REPAIR_HELD', 'Repair-held'), ('DEMO', 'Demo'), ('IN_TRANSIT', 'In-transit')], max_length=20)),
                ('reference_type', models.CharField(blank=True, max_length=60)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='organization.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='inventory.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='inventory.stocklocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='organization.company')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='masters.paymentterm')),
            ],
            options={
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.supplier'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_product_category_code'),
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'bin_code'), name='unique_stock_location_bin'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('product', 'location', 'condition'), name='unique_stock_item_balance'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='nonnegative_stock_quantity'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'movement_type', '-created_at'], name='stock_movement_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-created_at'], name='stock_movement_product_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='stock_movement_reference_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('company', 'movement_number'), name='unique_stock_movement_number'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_supplier_code'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'brand', 'part_number'], name='product_brand_part_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'internal_code'), name='unique_product_internal_code'),
        ),
    ]
