import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, ArrowLeft, CheckCircle2, ClipboardCheck, FileText, History, PauseCircle, PlayCircle, Save, Send, UserRoundCheck, Users, XCircle } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Field, FieldLabel } from "@/components/ui/field";
import { Separator } from "@/components/ui/separator";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { ERPEmptyState, ERPErrorState, ERPLoadingState, ERPPageHeader, ERPStatusBadge, NextActionPanel, formatDateTime } from "@/production/components/shared";
import { PanelJobsCard } from "@/production/components/panel-jobs-card";
import { apiGet, apiPost } from "@/production/lib/api";
import { hasPermission, useCurrentUser } from "@/production/lib/auth";
import { useRealtimeEntity } from "@/production/lib/realtime";
import { employeeLabel } from "@/production/lib/terminology";
import type { Project, ProjectClarification, ProjectHandoff } from "@/production/lib/sales-types";

type HandoffDraft = Pick<ProjectHandoff, "record_version" | "project_scope_summary" | "technical_requirement_summary" | "customer_specifications" | "special_commercial_commitments" | "technical_assumptions" | "open_questions" | "sales_notes">;

function money(value: string, currency = "INR") { return `${currency} ${Number(value).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`; }

export default function ProjectPage() {
  const { projectId = "" } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { data: user } = useCurrentUser();
  const [draft, setDraft] = useState<HandoffDraft | null>(null);
  const [clarificationOpen, setClarificationOpen] = useState(false);
  const [question, setQuestion] = useState("");
  const [activeClarification, setActiveClarification] = useState<ProjectClarification | null>(null);
  const [response, setResponse] = useState("");
  const [projectAction, setProjectAction] = useState<"hold" | "cancel" | null>(null);
  const [projectActionReason, setProjectActionReason] = useState("");
  const query = useQuery({ queryKey: ["project", projectId], queryFn: () => apiGet<Project>(`/projects/${projectId}/`), enabled: Boolean(projectId) });
  const project = query.data;
  const viewers = useRealtimeEntity("project", projectId);
  useEffect(() => { if (project?.engineering_handoff) { const handoff = project.engineering_handoff; setDraft({ record_version: handoff.record_version, project_scope_summary: handoff.project_scope_summary, technical_requirement_summary: handoff.technical_requirement_summary, customer_specifications: handoff.customer_specifications, special_commercial_commitments: handoff.special_commercial_commitments, technical_assumptions: handoff.technical_assumptions, open_questions: handoff.open_questions, sales_notes: handoff.sales_notes }); } }, [project]);
  const refresh = async () => { await queryClient.invalidateQueries({ queryKey: ["project", projectId] }); await queryClient.invalidateQueries({ queryKey: ["projects"] }); };
  const action = useMutation({ mutationFn: ({ path, body }: { path: string; body?: unknown }) => apiPost(path, body), onSuccess: async () => { await refresh(); setClarificationOpen(false); setQuestion(""); setActiveClarification(null); setResponse(""); setProjectAction(null); setProjectActionReason(""); } });
  const save = useMutation({ mutationFn: () => apiPost(`/projects/${projectId}/update-handoff/`, draft), onSuccess: refresh });
  if (query.isPending || !project || !draft) return <ERPLoadingState rows={10} />;
  if (query.isError) return <ERPErrorState message={query.error.message} />;
  const order = project.sales_order_detail;
  const revision = order.current_revision;
  const handoff = project.engineering_handoff;
  const handoffEditable = ["DRAFT", "CLARIFICATION_REQUIRED"].includes(handoff.status) && hasPermission(user, "projects.handoff.prepare");
  const run = (path: string, body?: unknown) => action.mutate({ path, body });
  const updateDraft = (field: keyof HandoffDraft, value: string) => setDraft((current) => current ? { ...current, [field]: value } : current);

  return <div className="mx-auto flex max-w-[1580px] flex-col gap-5">
    <ERPPageHeader eyebrow="Operations · Project 360" title={project.project_number} description={`${project.customer_name} · ${project.project_name} · commercial baseline ${project.current_commercial_baseline}`} actions={<><Button variant="outline" onClick={() => navigate("/app/projects")}><ArrowLeft data-icon="inline-start" />Projects</Button>{viewers.length ? <span className="rounded-full border bg-muted/40 px-3 py-1.5 text-xs text-muted-foreground"><Users className="mr-1 inline size-3" />{viewers.length} here</span> : null}<ERPStatusBadge value={project.status} label={project.status_label} />{project.status === "ON_HOLD" && hasPermission(user, "projects.project.hold") ? <Button variant="outline" onClick={() => run(`/projects/${project.id}/resume/`)}><PlayCircle data-icon="inline-start" />Resume</Button> : project.status !== "CANCELLED" && hasPermission(user, "projects.project.hold") ? <Button variant="outline" onClick={() => setProjectAction("hold")}><PauseCircle data-icon="inline-start" />Hold</Button> : null}{project.status !== "CANCELLED" && hasPermission(user, "projects.project.cancel") ? <Button variant="destructive" onClick={() => setProjectAction("cancel")}><XCircle data-icon="inline-start" />Cancel</Button> : null}</>} />
    {project.commercial_change_pending ? <Alert className="border-status-critical/40"><AlertTriangle /><AlertTitle>Sales Order changed after Workshop handoff</AlertTitle><AlertDescription>Review the changed commercial revision before continuing. Current: {project.current_commercial_baseline}; previous: {project.previous_commercial_baseline || "earlier baseline"}.{hasPermission(user, "projects.handoff.acknowledge_commercial_change") ? <Button className="mt-3" variant="outline" onClick={() => run(`/projects/${project.id}/acknowledge-commercial-change/`)}>I reviewed this change</Button> : null}</AlertDescription></Alert> : null}
    <NextActionPanel status={project.status} statusText={project.status_label} title={employeeLabel(project.next_action)} description={handoff.status === "DRAFT" ? "Sales should complete the practical scope and send it to Workshop." : handoff.status === "READY_FOR_ENGINEERING" ? "A Workshop employee can safely take ownership of this project work." : handoff.status === "CLARIFICATION_REQUIRED" ? "Sales must answer the open Workshop question before acceptance." : handoff.status === "ACCEPTED" ? "Create a Panel Job to start Workshop Review and material planning." : "The released commercial baseline remains the source of truth for this project."} primaryAction={handoff.status === "DRAFT" && hasPermission(user, "projects.handoff.submit") ? <Button onClick={() => run(`/projects/${project.id}/submit-handoff/`)} disabled={action.isPending || !draft.project_scope_summary.trim() || !draft.technical_requirement_summary.trim()}><Send data-icon="inline-start" />Send to Workshop</Button> : handoff.status === "READY_FOR_ENGINEERING" && !project.engineering_owner_name && hasPermission(user, "projects.handoff.take_ownership") ? <Button onClick={() => run(`/projects/${project.id}/take-ownership/`)} disabled={action.isPending}><UserRoundCheck data-icon="inline-start" />Take This</Button> : ["ENGINEERING_REVIEWING", "CLARIFICATION_REQUIRED"].includes(handoff.status) && project.open_clarification_count === 0 && hasPermission(user, "projects.handoff.accept") ? <Button onClick={() => run(`/projects/${project.id}/accept-handoff/`)}><CheckCircle2 data-icon="inline-start" />Mark Workshop Accepted</Button> : undefined} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card><CardContent className="p-4"><p className="text-xs uppercase tracking-[0.12em] text-muted-foreground">Sales owner</p><p className="mt-2 font-semibold">{project.sales_owner_name}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs uppercase tracking-[0.12em] text-muted-foreground">Workshop owner</p><p className="mt-2 font-semibold">{project.engineering_owner_name || "Unassigned"}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs uppercase tracking-[0.12em] text-muted-foreground">Target completion</p><p className="mt-2 font-semibold">{project.target_completion || "Not set"}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs uppercase tracking-[0.12em] text-muted-foreground">Open questions</p><p className="mt-2 text-xl font-semibold">{project.open_clarification_count}</p></CardContent></Card></div>
    {action.isError ? <ERPErrorState title="Action could not be completed" message={action.error.message} /> : null}{save.isError ? <ERPErrorState title="Handoff could not be saved" message={save.error.message} /> : null}
    <Tabs defaultValue="overview" className="gap-4"><TabsList className="h-auto w-full justify-start overflow-x-auto"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="commercial">Commercial</TabsTrigger><TabsTrigger value="po">Customer PO</TabsTrigger><TabsTrigger value="handoff">Workshop handoff</TabsTrigger><TabsTrigger value="panel-jobs">Panel Jobs</TabsTrigger><TabsTrigger value="documents">Documents</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger></TabsList>
      <TabsContent value="overview" className="mt-0"><div className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]"><Card><CardHeader><CardTitle>Project snapshot</CardTitle><CardDescription>The few facts staff need to act confidently.</CardDescription></CardHeader><CardContent><dl className="grid gap-x-6 gap-y-4 text-sm sm:grid-cols-2">{[["Customer", project.customer_name],["Customer reference", project.customer_project_reference || "Not provided"],["Site", project.site_name || "Not specified"],["Customer PO", project.customer_po_reference || "Pending / not linked"],["Sales Order", order.sales_order_number],["Priority", project.priority_label],["Delivery commitment", project.customer_delivery_commitment || "See Sales Order"],["Commercial baseline", project.current_commercial_baseline]].map(([label, value]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl></CardContent></Card><Card className="border-primary/20"><CardHeader><CardTitle>Ownership and handoff</CardTitle><CardDescription>One clear owner at each department boundary.</CardDescription></CardHeader><CardContent className="grid gap-4"><div className="rounded-lg border p-4"><div className="flex justify-between gap-3"><div><p className="text-xs text-muted-foreground">Handoff status</p><p className="mt-1 font-semibold">{employeeLabel(handoff.status_label)}</p></div><ERPStatusBadge value={handoff.status} /></div></div><p className="text-sm text-muted-foreground">Use the next-action panel above to move this handoff forward.</p></CardContent></Card></div></TabsContent>
      <TabsContent value="commercial" className="mt-0"><div className="grid gap-4 lg:grid-cols-[1fr_340px]"><Card><CardHeader><CardTitle>Released commercial order</CardTitle><CardDescription>Workshop sees commitments and scope, not confidential cost or margin.</CardDescription></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>#</TableHead><TableHead>Description</TableHead><TableHead>Quantity</TableHead><TableHead>Delivery</TableHead></TableRow></TableHeader><TableBody>{revision.lines.map((line) => <TableRow key={line.id}><TableCell>{line.line_number}</TableCell><TableCell><p className="font-medium">{line.description}</p>{line.customer_visible_note ? <p className="text-xs text-muted-foreground">{line.customer_visible_note}</p> : null}</TableCell><TableCell>{Number(line.quantity).toLocaleString("en-IN")} {line.unit_of_measure}</TableCell><TableCell>{line.delivery_text || revision.promised_delivery || "See order terms"}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card><Card><CardHeader><CardTitle>Commitments</CardTitle><CardDescription>Authoritative terms from the released revision.</CardDescription></CardHeader><CardContent className="grid gap-3 text-sm">{[["Order value", money(revision.grand_total, revision.currency_code)],["Payment", revision.payment_terms || "Not specified"],["Delivery", revision.delivery_terms || "Not specified"],["Warranty", revision.warranty_terms || "Not specified"],["Installation", revision.installation_terms || "Not specified"]].map(([label, value]) => <div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="font-medium">{value}</p></div>)}<Separator /><Link to={`/app/sales/orders/${order.id}`}><Button variant="outline" className="w-full"><ClipboardCheck data-icon="inline-start" />Open Sales Order</Button></Link></CardContent></Card></div></TabsContent>
      <TabsContent value="po" className="mt-0"><Card><CardHeader><CardTitle>Customer purchase order</CardTitle><CardDescription>The original customer record and every revision remain in the controlled PO register.</CardDescription></CardHeader><CardContent>{project.customer_po_detail ? <div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">PO number</p><p className="font-semibold">{project.customer_po_detail.po_number}</p></div><div><p className="text-xs text-muted-foreground">Current revision</p><p className="font-semibold">Revision {project.customer_po_detail.current_revision.revision_number}</p></div><div><p className="text-xs text-muted-foreground">Quotation comparison</p><div className="mt-1"><ERPStatusBadge value={project.customer_po_detail.current_revision.match_status} label={project.customer_po_detail.current_revision.match_status_label} /></div></div>{project.customer_po_detail.current_revision.supporting_document ? <Link className="sm:col-span-3" to={`/app/documents/${project.customer_po_detail.current_revision.supporting_document}`}><Button variant="outline"><FileText data-icon="inline-start" />Open PO document</Button></Link> : null}</div> : <ERPEmptyState title="Customer PO pending or not linked" description="Sales can link it to the Sales Order later without changing this released baseline silently." />}</CardContent></Card></TabsContent>
      <TabsContent value="handoff" className="mt-0"><div className="grid gap-4 lg:grid-cols-[1fr_420px]"><Card><CardHeader className="gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle>Sales → Workshop handoff</CardTitle><CardDescription>Plain-language scope, customer requirements, commitments, assumptions, and open questions.</CardDescription></div>{handoffEditable ? <Button onClick={() => save.mutate()} disabled={save.isPending}><Save data-icon="inline-start" />Save handoff</Button> : null}</CardHeader><CardContent className="grid gap-4">{([['project_scope_summary','Project scope'],['technical_requirement_summary','Technical requirement'],['customer_specifications','Customer specifications'],['special_commercial_commitments','Special commercial commitments'],['technical_assumptions','Technical assumptions'],['open_questions','Open questions'],['sales_notes','Sales notes']] as const).map(([field, label]) => <Field key={field}><FieldLabel htmlFor={`handoff-${field}`}>{label}</FieldLabel><Textarea id={`handoff-${field}`} rows={field === "project_scope_summary" ? 4 : 3} disabled={!handoffEditable} value={draft[field]} onChange={(event) => updateDraft(field, event.target.value)} /></Field>)}{handoff.status === "DRAFT" && hasPermission(user, "projects.handoff.submit") ? <Button onClick={() => run(`/projects/${project.id}/submit-handoff/`)} disabled={action.isPending || !draft.project_scope_summary.trim() || !draft.technical_requirement_summary.trim()}><Send data-icon="inline-start" />Send to Workshop</Button> : null}</CardContent></Card><Card><CardHeader><CardTitle>Questions and answers</CardTitle><CardDescription>Resolve missing details inside the Project rather than losing them in WhatsApp.</CardDescription></CardHeader><CardContent>{!handoff.clarifications.length ? <ERPEmptyState title="No clarifications" description="Workshop can ask Sales when a requirement is unclear." /> : <div className="grid gap-3">{handoff.clarifications.map((item) => <div key={item.id} className="rounded-lg border p-4"><div className="flex justify-between gap-3"><p className="font-semibold">{item.question}</p><ERPStatusBadge value={item.status} /></div><p className="mt-1 text-xs text-muted-foreground">Asked by {item.requested_by_name} · {formatDateTime(item.created_at)}</p>{item.response ? <div className="mt-3 rounded-md bg-status-success/5 p-3"><p className="text-xs text-muted-foreground">Sales response</p><p className="mt-1 text-sm">{item.response}</p></div> : hasPermission(user, "projects.handoff.respond_clarification") ? <Button className="mt-3" size="sm" variant="outline" onClick={() => setActiveClarification(item)}>Respond</Button> : null}</div>)}</div>}</CardContent></Card></div></TabsContent>
      <TabsContent value="panel-jobs" className="mt-0"><PanelJobsCard projectId={project.id} projectStatus={project.status} /></TabsContent>
      <TabsContent value="documents" className="mt-0"><Card><CardHeader><CardTitle>Project documents</CardTitle><CardDescription>Private shared Documents linked to this project. Drawing Management has not been started.</CardDescription></CardHeader><CardContent>{!project.documents.length ? <ERPEmptyState title="No project documents linked" description="Customer PO and Sales Order records remain available in their own controlled tabs." /> : <div className="grid gap-3 sm:grid-cols-2">{project.documents.map((document) => <Link key={document.id} to={`/app/documents/${document.id}`} className="rounded-lg border p-4 hover:border-primary/50"><div className="flex items-start gap-3"><FileText className="text-primary" /><div><p className="font-semibold">{document.title}</p><p className="text-xs text-muted-foreground">{document.category} · {document.filename}</p></div></div></Link>)}</div>}</CardContent></Card></TabsContent>
      <TabsContent value="activity" className="mt-0"><Card><CardHeader><CardTitle className="flex items-center gap-2"><History className="text-primary" />Project activity</CardTitle><CardDescription>Audited commercial and handoff decisions for this Project.</CardDescription></CardHeader><CardContent>{!project.activity.length ? <ERPEmptyState title="No visible activity" description="Activity appears here as the Project moves through handoff." /> : <div className="relative ml-2 border-l pl-6">{project.activity.map((event) => <div key={event.id} className="relative pb-6 last:pb-0"><span className="absolute -left-[29px] top-1 size-2 rounded-full bg-primary" /><p className="font-medium">{event.summary}</p><p className="text-xs text-muted-foreground">{event.actor} · {formatDateTime(event.occurred_at)}</p></div>)}</div>}</CardContent></Card></TabsContent>
    </Tabs>
    <Dialog open={clarificationOpen} onOpenChange={setClarificationOpen}><DialogContent><DialogHeader><DialogTitle>Ask Sales for clarification</DialogTitle><DialogDescription>Ask one clear operational question. Sales will see it in the Project and notifications.</DialogDescription></DialogHeader><Field><FieldLabel htmlFor="project-question">Question</FieldLabel><Textarea id="project-question" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="What exact detail is needed before Workshop can accept?" /></Field><DialogFooter><Button variant="outline" onClick={() => setClarificationOpen(false)}>Cancel</Button><Button disabled={!question.trim() || action.isPending} onClick={() => run(`/projects/${project.id}/request-clarification/`, { question })}>Send question</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(activeClarification)} onOpenChange={(value) => !value && setActiveClarification(null)}><DialogContent><DialogHeader><DialogTitle>Respond to Workshop</DialogTitle><DialogDescription>{activeClarification?.question}</DialogDescription></DialogHeader><Field><FieldLabel htmlFor="clarification-response">Sales response</FieldLabel><Textarea id="clarification-response" value={response} onChange={(event) => setResponse(event.target.value)} placeholder="Give the clear, confirmed answer and reference any customer evidence." /></Field><DialogFooter><Button variant="outline" onClick={() => setActiveClarification(null)}>Cancel</Button><Button disabled={!response.trim() || action.isPending} onClick={() => activeClarification && run(`/project-clarifications/${activeClarification.id}/respond/`, { response })}>Send response</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(projectAction)} onOpenChange={(value) => !value && setProjectAction(null)}><DialogContent><DialogHeader><DialogTitle>{projectAction === "hold" ? "Put Project on hold" : "Cancel Project"}</DialogTitle><DialogDescription>{projectAction === "hold" ? "Pause work while preserving the order, ownership, and complete history." : "Cancellation is audited and keeps the Project record for reference."}</DialogDescription></DialogHeader><Field><FieldLabel htmlFor="project-action-reason">Business reason</FieldLabel><Textarea id="project-action-reason" value={projectActionReason} onChange={(event) => setProjectActionReason(event.target.value)} /></Field><DialogFooter><Button variant="outline" onClick={() => setProjectAction(null)}>Back</Button><Button variant={projectAction === "cancel" ? "destructive" : "default"} disabled={!projectActionReason.trim() || action.isPending} onClick={() => run(`/projects/${project.id}/${projectAction}/`, { reason: projectActionReason })}>Confirm</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
