# Generated by Django 5.2.17 on 2026-08-18 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEngineeringHandoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('project_scope_summary', models.TextField(blank=True)),
                ('technical_requirement_summary', models.TextField(blank=True)),
                ('customer_specifications', models.TextField(blank=True)),
                ('special_commercial_commitments', models.TextField(blank=True)),
                ('technical_assumptions', models.TextField(blank=True)),
                ('open_questions', models.TextField(blank=True)),
                ('sales_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Preparing Handoff'), ('READY_FOR_ENGINEERING', 'Ready for Engineering'), ('ENGINEERING_REVIEWING', 'Engineering Reviewing'), ('CLARIFICATION_REQUIRED', 'Sales Clarification Needed'), ('ACCEPTED', 'Engineering Accepted')], default='DRAFT', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('clarification_requested_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectHandoffClarification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Waiting for Sales'), ('ANSWERED', 'Answered'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('project_number', models.CharField(max_length=80)),
                ('project_name', models.CharField(max_length=250)),
                ('customer_project_reference', models.CharField(blank=True, max_length=250)),
                ('customer_po_reference', models.CharField(blank=True, max_length=250)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=16)),
                ('status', models.CharField(choices=[('NEW', 'New Project'), ('HANDOFF_PENDING', 'Waiting for Engineering'), ('ENGINEERING_REVIEW', 'Engineering Reviewing'), ('ENGINEERING_ACCEPTED', 'Engineering Accepted'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=28)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('target_completion', models.DateField(blank=True, null=True)),
                ('customer_delivery_commitment', models.CharField(blank=True, max_length=500)),
                ('internal_notes', models.TextField(blank=True)),
                ('commercial_change_pending', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='organization.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
