# Generated by Django 5.2.17 on 2026-08-18 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_crmactivity_enquiry'),
        ('documents', '0001_initial'),
        ('organization', '0001_initial'),
        ('projects', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_sales_order_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_commercial_baselines', to='sales.salesorderrevision'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='project',
            name='engineering_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engineering_projects', to='organization.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='previous_sales_order_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_project_commercial_baselines', to='sales.salesorderrevision'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to='organization.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_projects', to='organization.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.customersite'),
        ),
        migrations.AddField(
            model_name='projectengineeringhandoff',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_project_handoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectengineeringhandoff',
            name='accepted_customer_po_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_project_handoffs', to='sales.customerpurchaseorderrevision'),
        ),
        migrations.AddField(
            model_name='projectengineeringhandoff',
            name='accepted_sales_order_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_project_handoffs', to='sales.salesorderrevision'),
        ),
        migrations.AddField(
            model_name='projectengineeringhandoff',
            name='assigned_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_project_handoffs', to='organization.employee'),
        ),
        migrations.AddField(
            model_name='projectengineeringhandoff',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='engineering_handoff', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectengineeringhandoff',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_project_handoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecthandoffclarification',
            name='handoff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clarifications', to='projects.projectengineeringhandoff'),
        ),
        migrations.AddField(
            model_name='projecthandoffclarification',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_project_clarifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecthandoffclarification',
            name='respond_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_clarifications_to_answer', to='organization.employee'),
        ),
        migrations.AddField(
            model_name='projecthandoffclarification',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_project_clarifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecthandoffclarification',
            name='response_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_clarification_responses', to='documents.document'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'status', '-updated_at'], name='project_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['engineering_owner', 'status'], name='project_engineering_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('company', 'project_number'), name='unique_company_project_number'),
        ),
    ]
