# Generated by Django 5.2.17 on 2026-08-09 22:00

import apps.numbering.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('financial_year', models.CharField(max_length=9)),
                ('template', models.CharField(default='{company}/{code}/{fy}/{number}', max_length=160, validators=[apps.numbering.models.validate_number_template])),
                ('next_number', models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('padding', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('reset_behavior', models.CharField(choices=[('NEVER', 'Never'), ('FINANCIAL_YEAR', 'Financial year')], default='FINANCIAL_YEAR', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='organization.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='organization.company')),
            ],
            options={
                'ordering': ['company__name', 'code', 'financial_year', 'branch__name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'branch', 'code', 'financial_year'), name='unique_document_sequence', nulls_distinct=False)],
            },
        ),
    ]
