# Generated by Django 5.2.17 on 2026-08-10 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=120)),
                ('module', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=100)),
                ('entity_reference', models.CharField(blank=True, max_length=250)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('ARCHIVE', 'Archived'), ('RESTORE', 'Restored'), ('SUBMIT', 'Submitted'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('CANCEL', 'Cancelled'), ('ACTIVATE', 'Activated'), ('DEACTIVATE', 'Deactivated'), ('LOGIN', 'Signed in'), ('LOGOUT', 'Signed out'), ('DOWNLOAD', 'Downloaded'), ('EXPORT', 'Exported'), ('UPLOAD', 'Uploaded'), ('VERSION_CREATE', 'Version added'), ('STATUS_CHANGE', 'Status changed'), ('ASSIGN', 'Assigned'), ('UNASSIGN', 'Unassigned')], max_length=30)),
                ('occurred_at', models.DateTimeField()),
                ('source', models.CharField(default='ERP', max_length=40)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('summary', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='organization.employee')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.company')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['company', '-occurred_at'], name='audit_company_time_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_entity_idx'), models.Index(fields=['actor_user', '-occurred_at'], name='audit_actor_idx'), models.Index(fields=['action', '-occurred_at'], name='audit_action_idx')],
            },
        ),
    ]
