# Generated by Django 5.2.17 on 2026-08-10 09:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Needs action'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED_FOR_CHANGES', 'Returned for changes'), ('SKIPPED', 'No longer required'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['step', 'approver_name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_name', models.CharField(max_length=180)),
                ('workflow_version_number', models.PositiveIntegerField()),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=100)),
                ('entity_reference', models.CharField(max_length=250)),
                ('requested_by_name', models.CharField(max_length=200)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED_FOR_CHANGES', 'Returned for changes'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('submission_comment', models.TextField(blank=True)),
                ('snapshot_metadata', models.JSONField(blank=True, default=dict)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='organization.company')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStepDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=180)),
                ('approval_mode', models.CharField(choices=[('SINGLE', 'Any one approver'), ('PARALLEL', 'Parallel approvals')], default='SINGLE', max_length=20)),
                ('resolver_type', models.CharField(choices=[('PERMISSION', 'Permission-based'), ('SPECIFIC_USERS', 'Specific users')], max_length=30)),
                ('required_permission_code', models.CharField(blank=True, max_length=160)),
                ('scope_logic', models.CharField(default='COMPANY', max_length=30)),
                ('minimum_approvals', models.PositiveIntegerField(default=1)),
                ('allow_reject', models.BooleanField(default=True)),
                ('allow_return_for_changes', models.BooleanField(default=True)),
                ('sla_duration', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('specific_users', models.ManyToManyField(blank=True, related_name='specific_approval_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['workflow_version', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStepInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('step_name', models.CharField(max_length=180)),
                ('approval_mode', models.CharField(choices=[('SINGLE', 'Any one approver'), ('PARALLEL', 'Parallel approvals')], max_length=20)),
                ('minimum_approvals', models.PositiveIntegerField(default=1)),
                ('allow_reject', models.BooleanField(default=True)),
                ('allow_return_for_changes', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('OPEN', 'Needs approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED_FOR_CHANGES', 'Returned for changes'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=30)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_metadata', models.JSONField(blank=True, default=dict)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='approvals.approvalstepdefinition')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='approvals.approvalrequest')),
            ],
            options={
                'ordering': ['request', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_requests', to='approvals.approvalstepinstance'),
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by_name', models.CharField(max_length=200)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED_FOR_CHANGES', 'Returned for changes')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision_record', to='approvals.approvalassignment')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='approvals.approvalstepinstance')),
            ],
            options={
                'ordering': ['decided_at'],
            },
        ),
        migrations.AddField(
            model_name='approvalassignment',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='approvals.approvalstepinstance'),
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_workflows', to='organization.company')),
            ],
            options={
                'ordering': ['company__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('allow_self_approval', models.BooleanField(default=False)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_workflow_versions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='approvals.approvalworkflow')),
            ],
            options={
                'ordering': ['workflow', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_workflows', to='approvals.approvalworkflowversion'),
        ),
        migrations.AddField(
            model_name='approvalstepdefinition',
            name='workflow_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='approvals.approvalworkflowversion'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='workflow_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='approvals.approvalworkflowversion'),
        ),
        migrations.CreateModel(
            name='ApprovalCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('EQ', 'Equals'), ('NE', 'Does not equal'), ('GT', 'Greater than'), ('GTE', 'Greater than or equal'), ('LT', 'Less than'), ('LTE', 'Less than or equal'), ('IN', 'In list')], max_length=10)),
                ('value', models.JSONField()),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='approvals.approvalworkflowversion')),
            ],
            options={
                'ordering': ['workflow_version', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='approvalstepinstance',
            constraint=models.UniqueConstraint(fields=('request', 'sequence'), name='unique_approval_request_step'),
        ),
        migrations.AddConstraint(
            model_name='approvalassignment',
            constraint=models.UniqueConstraint(fields=('step', 'approver'), name='unique_approval_step_approver'),
        ),
        migrations.AddConstraint(
            model_name='approvalworkflowversion',
            constraint=models.UniqueConstraint(fields=('workflow', 'version_number'), name='unique_approval_workflow_version'),
        ),
        migrations.AddConstraint(
            model_name='approvalworkflowversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gt', 0)), name='positive_approval_workflow_version'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['company', 'entity_type', 'is_active'], name='approval_workflow_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalworkflow',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_approval_workflow_code'),
        ),
        migrations.AddConstraint(
            model_name='approvalstepdefinition',
            constraint=models.UniqueConstraint(fields=('workflow_version', 'sequence'), name='unique_approval_step_sequence'),
        ),
        migrations.AddConstraint(
            model_name='approvalstepdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='positive_approval_step_sequence'),
        ),
        migrations.AddConstraint(
            model_name='approvalstepdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_approvals__gt', 0)), name='positive_minimum_approvals'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['company', 'status', '-requested_at'], name='approval_request_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['entity_type', 'entity_id'], name='approval_request_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requested_by', '-requested_at'], name='approval_request_submitter_idx'),
        ),
    ]
