# Generated by Django 5.2.17 on 2026-08-11 00:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiries', '0002_enquiry_cancellation_reason'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringFeasibilityReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In review'), ('CLARIFICATION_REQUIRED', 'Clarification required'), ('FEASIBLE', 'Feasible'), ('NOT_FEASIBLE', 'Not feasible'), ('CANCELLED', 'Cancelled'), ('SUPERSEDED', 'Superseded')], default='PENDING', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('FEASIBLE', 'Feasible'), ('FEASIBLE_WITH_CONDITIONS', 'Feasible with conditions'), ('NOT_FEASIBLE', 'Not feasible')], max_length=32)),
                ('technical_summary', models.TextField(blank=True)),
                ('feasibility_notes', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('exclusions', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('special_materials', models.TextField(blank=True)),
                ('outsourced_processes', models.TextField(blank=True)),
                ('tooling_requirements', models.TextField(blank=True)),
                ('testing_requirements', models.TextField(blank=True)),
                ('customer_clarification_summary', models.TextField(blank=True)),
                ('preliminary_drawing_notes', models.TextField(blank=True)),
                ('preliminary_bom_notes', models.TextField(blank=True)),
                ('preliminary_routing_notes', models.TextField(blank=True)),
                ('engineering_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999.99'))])),
                ('manufacturing_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999.99'))])),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_comment', models.TextField(blank=True)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engineering_feasibility_reviews', to='organization.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engineering_reviews', to='organization.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_engineering_reviews', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_engineering_reviews', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engineering_reviews', to='enquiries.enquiry')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_engineering_reviews', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='engineering_reviews.engineeringfeasibilityreview')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringClarification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=250)),
                ('question', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField()),
                ('response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_comment', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engineering_clarifications', to='organization.employee')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_engineering_clarifications', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engineering_clarifications', to='organization.company')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_engineering_clarifications', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_engineering_clarifications', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clarifications', to='engineering_reviews.engineeringfeasibilityreview')),
            ],
            options={
                'ordering': ['status', 'due_at', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='engineeringfeasibilityreview',
            index=models.Index(fields=['company', 'status', '-created_at'], name='eng_review_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringfeasibilityreview',
            index=models.Index(fields=['assigned_engineer', 'status'], name='eng_review_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringfeasibilityreview',
            index=models.Index(fields=['enquiry', '-revision_number'], name='eng_review_revision_idx'),
        ),
        migrations.AddConstraint(
            model_name='engineeringfeasibilityreview',
            constraint=models.UniqueConstraint(fields=('enquiry', 'revision_number'), name='unique_engineering_review_revision'),
        ),
        migrations.AddConstraint(
            model_name='engineeringfeasibilityreview',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('enquiry',), name='unique_current_engineering_review'),
        ),
        migrations.AddConstraint(
            model_name='engineeringfeasibilityreview',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gt', 0)), name='positive_engineering_review_revision'),
        ),
        migrations.AddIndex(
            model_name='engineeringclarification',
            index=models.Index(fields=['review', 'status'], name='eng_clarification_review_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringclarification',
            index=models.Index(fields=['assigned_to', 'status', 'due_at'], name='eng_clarification_owner_idx'),
        ),
    ]
