# Generated by Django 5.2.17 on 2026-09-06 04:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_crmactivity_enquiry'),
        ('inventory', '0001_initial'),
        ('organization', '0002_branch_record_version_company_record_version_and_more'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('equipment_name', models.CharField(max_length=250)),
                ('make_model', models.CharField(blank=True, max_length=250)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_equipment', to='organization.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='crm.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_equipment', to='inventory.product')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='crm.customersite')),
            ],
            options={
                'ordering': ['customer__legal_name', 'equipment_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('ticket_number', models.CharField(max_length=80)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('INDIAMART', 'IndiaMART'), ('TRADEINDIA', 'TradeIndia'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('CALL', 'Call'), ('WALK_IN', 'Walk-in'), ('REFERRAL', 'Referral'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('complaint', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=16)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('AWAITING_PARTS', 'Awaiting Parts'), ('UNDER_REPAIR', 'Under Repair'), ('AWAITING_CUSTOMER_APPROVAL', 'Awaiting Customer Approval'), ('READY_FOR_DISPATCH', 'Ready for Dispatch'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=32)),
                ('scheduled_visit_at', models.DateTimeField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('repair_notes', models.TextField(blank=True)),
                ('warranty_claim', models.BooleanField(default=False)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_reference', models.CharField(blank=True, max_length=250)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_service_tickets', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='organization.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='crm.customercontact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='crm.customer')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='service.equipment')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='quotations.quotation')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_service_tickets', to='organization.employee')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceJobLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('line_number', models.PositiveIntegerField()),
                ('line_type', models.CharField(choices=[('PART', 'Part'), ('LABOUR', 'Labour')], max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('consumed_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_job_lines', to='inventory.product')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_lines', to='service.serviceticket')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTicketStageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_ticket_stage_events', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_events', to='service.serviceticket')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['company', 'customer'], name='equipment_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='equipment_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['company', 'status', '-updated_at'], name='service_ticket_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['technician', 'status'], name='service_ticket_technician_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['customer', '-created_at'], name='service_ticket_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceticket',
            constraint=models.UniqueConstraint(fields=('company', 'ticket_number'), name='unique_service_ticket_number'),
        ),
        migrations.AddConstraint(
            model_name='servicejobline',
            constraint=models.UniqueConstraint(fields=('ticket', 'line_number'), name='unique_service_job_line'),
        ),
        migrations.AddConstraint(
            model_name='servicejobline',
            constraint=models.CheckConstraint(condition=models.Q(('line_number__gt', 0)), name='positive_service_line_number'),
        ),
        migrations.AddIndex(
            model_name='serviceticketstageevent',
            index=models.Index(fields=['ticket', '-occurred_at'], name='service_ticket_stage_idx'),
        ),
    ]
