# Generated by Django 5.2.17 on 2026-09-06 00:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('organization', '0002_branch_record_version_company_record_version_and_more'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('panel_job_number', models.CharField(max_length=80)),
                ('panel_name', models.CharField(max_length=250)),
                ('panel_reference', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('REQUIREMENT_REVIEW', 'Workshop Review'), ('MATERIAL_PLANNING', 'Material Planning'), ('MATERIAL_SHORTAGE', 'Material Shortage'), ('READY_FOR_ASSEMBLY', 'Ready for Assembly'), ('ASSEMBLY', 'Assembly'), ('WIRING', 'Wiring'), ('TESTING', 'Testing'), ('QUALITY_CHECK', 'Quality Check'), ('FITTING_INSTALLATION', 'Fitting / Installation'), ('HANDOVER', 'Handover'), ('CLOSED', 'Closed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='REQUIREMENT_REVIEW', max_length=24)),
                ('requirement_notes', models.TextField(blank=True)),
                ('target_completion', models.DateField(blank=True, null=True)),
                ('quality_check_notes', models.TextField(blank=True)),
                ('quality_passed', models.BooleanField(blank=True, null=True)),
                ('handover_notes', models.TextField(blank=True)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_jobs', to='organization.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_panel_jobs', to=settings.AUTH_USER_MODEL)),
                ('handed_over_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handed_over_panel_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_jobs', to='projects.project')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_jobs', to='organization.warehouse')),
                ('workshop_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_panel_jobs', to='organization.employee')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PanelJobMaterialLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('line_number', models.PositiveIntegerField()),
                ('required_quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('issued_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('consumed_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('returned_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('panel_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_lines', to='workshop.paneljob')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_job_material_lines', to='inventory.product')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='PanelJobStageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_job_stage_events', to=settings.AUTH_USER_MODEL)),
                ('panel_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_events', to='workshop.paneljob')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paneljob',
            index=models.Index(fields=['company', 'status', '-updated_at'], name='panel_job_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='paneljob',
            index=models.Index(fields=['project'], name='panel_job_project_idx'),
        ),
        migrations.AddIndex(
            model_name='paneljob',
            index=models.Index(fields=['workshop_owner', 'status'], name='panel_job_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='paneljob',
            constraint=models.UniqueConstraint(fields=('company', 'panel_job_number'), name='unique_panel_job_number'),
        ),
        migrations.AddConstraint(
            model_name='paneljobmaterialline',
            constraint=models.UniqueConstraint(fields=('panel_job', 'line_number'), name='unique_panel_job_material_line'),
        ),
        migrations.AddConstraint(
            model_name='paneljobmaterialline',
            constraint=models.CheckConstraint(condition=models.Q(('line_number__gt', 0)), name='positive_panel_job_line_number'),
        ),
        migrations.AddConstraint(
            model_name='paneljobmaterialline',
            constraint=models.CheckConstraint(condition=models.Q(('required_quantity__gt', 0)), name='positive_panel_job_required_quantity'),
        ),
        migrations.AddIndex(
            model_name='paneljobstageevent',
            index=models.Index(fields=['panel_job', '-occurred_at'], name='panel_job_stage_idx'),
        ),
    ]
