# Generated by Django 5.2.17 on 2026-08-11 12:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('engineering_reviews', '0001_initial'),
        ('enquiries', '0002_enquiry_cancellation_reason'),
        ('masters', '0002_india_defaults'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate_number', models.CharField(max_length=80)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PREPARATION', 'In preparation'), ('READY_FOR_REVIEW', 'Ready for review'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('RETURNED_FOR_CHANGES', 'Returned for changes'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32)),
                ('pricing_method', models.CharField(choices=[('MARKUP', 'Cost plus markup'), ('MARGIN', 'Target gross margin'), ('MANUAL', 'Manual selling price')], default='MARKUP', max_length=20)),
                ('markup_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999.9999'))])),
                ('target_margin_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.9999'))])),
                ('manual_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('proposed_selling_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('gross_margin_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('gross_margin_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=9)),
                ('category_totals', models.JSONField(blank=True, default=dict)),
                ('assumptions', models.TextField(blank=True)),
                ('exclusions', models.TextField(blank=True)),
                ('commercial_notes', models.TextField(blank=True)),
                ('technical_reference_summary', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_estimate', to='approvals.approvalrequest')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commercial_estimates', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_estimates', to='organization.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commercial_estimates', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_estimates', to='masters.currency')),
                ('engineering_review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_estimates', to='engineering_reviews.engineeringfeasibilityreview')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_estimates', to='enquiries.enquiry')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_commercial_estimates', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_commercial_estimates', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='estimation.commercialestimate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_commercial_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateCostLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('MATERIAL', 'Material'), ('LABOUR', 'Labour'), ('MACHINE', 'Machine'), ('SUBCONTRACT', 'Subcontract'), ('ENGINEERING', 'Engineering'), ('OVERHEAD', 'Overhead'), ('PACKING', 'Packing'), ('FREIGHT', 'Freight'), ('INSTALLATION', 'Installation'), ('TRAVEL', 'Travel'), ('OTHER', 'Other'), ('CONTINGENCY', 'Contingency')], max_length=24)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_of_measure', models.CharField(default='NOS', max_length=40)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('source_reference', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_lines', to='estimation.commercialestimate')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='commercialestimate',
            index=models.Index(fields=['company', 'status', '-created_at'], name='estimate_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialestimate',
            index=models.Index(fields=['enquiry', '-revision_number'], name='estimate_revision_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialestimate',
            index=models.Index(fields=['prepared_by', 'status'], name='estimate_preparer_idx'),
        ),
        migrations.AddConstraint(
            model_name='commercialestimate',
            constraint=models.UniqueConstraint(fields=('company', 'estimate_number', 'revision_number'), name='unique_estimate_revision'),
        ),
        migrations.AddConstraint(
            model_name='commercialestimate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('enquiry',), name='unique_current_estimate'),
        ),
        migrations.AddConstraint(
            model_name='commercialestimate',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gt', 0)), name='positive_estimate_revision'),
        ),
        migrations.AddConstraint(
            model_name='commercialestimate',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='nonnegative_estimate_cost'),
        ),
        migrations.AddConstraint(
            model_name='commercialestimate',
            constraint=models.CheckConstraint(condition=models.Q(('proposed_selling_price__gte', 0)), name='nonnegative_estimate_price'),
        ),
        migrations.AddIndex(
            model_name='estimatecostline',
            index=models.Index(fields=['estimate', 'category'], name='estimate_line_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='estimatecostline',
            constraint=models.UniqueConstraint(fields=('estimate', 'line_number'), name='unique_estimate_line'),
        ),
        migrations.AddConstraint(
            model_name='estimatecostline',
            constraint=models.CheckConstraint(condition=models.Q(('line_number__gt', 0)), name='positive_estimate_line'),
        ),
        migrations.AddConstraint(
            model_name='estimatecostline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='positive_estimate_quantity'),
        ),
        migrations.AddConstraint(
            model_name='estimatecostline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='nonnegative_estimate_unit_cost'),
        ),
        migrations.AddConstraint(
            model_name='estimatecostline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='nonnegative_estimate_amount'),
        ),
    ]
