# Generated by Django 5.2.17 on 2026-08-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_phase3_sales_project_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='record_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='permissionoverride',
            name='record_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='role',
            name='record_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='record_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='record_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
