# Generated by Django 5.2.17 on 2026-08-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='record_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='company',
            name='record_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='department',
            name='record_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='designation',
            name='record_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='record_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='record_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
