# Generated by Django 5.2.17 on 2026-08-09 22:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('country_code', models.CharField(default='IN', max_length=2)),
                ('financial_year_start_month', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('date_format', models.CharField(default='DD-MM-YYYY', max_length=30)),
                ('number_format', models.CharField(default='en-IN', max_length=30)),
                ('document_footer', models.TextField(blank=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organization.company')),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.currency')),
            ],
            options={
                'verbose_name_plural': 'company settings',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('is_enabled', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='organization.company')),
            ],
            options={
                'ordering': ['company__name', 'key'],
                'constraints': [models.UniqueConstraint(fields=('company', 'key'), name='unique_company_feature_flag')],
            },
        ),
    ]
