# Generated by Django 5.2.17 on 2026-08-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='record_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='record_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
