# Generated by Django 5.2.17 on 2026-08-10 20:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_india_defaults'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.CharField(max_length=80)),
                ('legal_name', models.CharField(max_length=250)),
                ('trade_name', models.CharField(blank=True, max_length=250)),
                ('customer_type', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('INDIVIDUAL', 'Individual'), ('GOVERNMENT', 'Government'), ('DEALER', 'Dealer / channel partner'), ('OTHER', 'Other')], default='ORGANIZATION', max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN.', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$')])),
                ('pan', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-character PAN.', regex='^[A-Z]{5}\\d{4}[A-Z]$')])),
                ('cin', models.CharField(blank=True, max_length=21)),
                ('industry', models.CharField(blank=True, max_length=160)),
                ('website', models.URLField(blank=True)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=30)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='PROSPECT', max_length=20)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_customers', to='organization.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='organization.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='masters.currency')),
                ('default_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='masters.taxrate')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='masters.paymentterm')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['legal_name', 'customer_code'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('alternate_phone', models.CharField(blank=True, max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='crm.customer')),
            ],
            options={
                'ordering': ['customer', '-is_primary', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('BILLING', 'Billing'), ('SHIPPING', 'Shipping'), ('SITE', 'Site'), ('REGISTERED', 'Registered'), ('OTHER', 'Other')], max_length=20)),
                ('label', models.CharField(max_length=160)),
                ('address_line_1', models.CharField(max_length=250)),
                ('address_line_2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('country', models.CharField(default='India', max_length=120)),
                ('postal_code', models.CharField(max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN.', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$')])),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='crm.customercontact')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='crm.customer')),
            ],
            options={
                'ordering': ['customer', 'address_type', '-is_default', 'label'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'status'], name='crm_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'legal_name'], name='crm_customer_name_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['account_manager', 'status'], name='crm_customer_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('company', 'customer_code'), name='unique_company_customer_code'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('gstin', ''), _negated=True), fields=('company', 'gstin'), name='unique_company_customer_gstin'),
        ),
        migrations.AddIndex(
            model_name='customercontact',
            index=models.Index(fields=['customer', 'is_active'], name='crm_contact_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('customer',), name='unique_active_primary_contact'),
        ),
        migrations.AddIndex(
            model_name='customersite',
            index=models.Index(fields=['customer', 'is_active'], name='crm_site_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='customersite',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('customer', 'address_type'), name='unique_active_default_site_type'),
        ),
    ]
