# Generated by Django 5.2.17 on 2026-08-10 20:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('WHATSAPP', 'WhatsApp'), ('SITE_VISIT', 'Site visit'), ('NOTE', 'Note'), ('FOLLOW_UP', 'Follow-up'), ('OTHER', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_activities', to='organization.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_crm_activities', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='crm.customercontact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='crm.customer')),
                ('follow_up_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_follow_ups', to='organization.employee')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['company', '-activity_date'], name='crm_activity_company_idx'), models.Index(fields=['follow_up_owner', 'status', 'next_follow_up_at'], name='crm_followup_queue_idx'), models.Index(fields=['customer', '-activity_date'], name='crm_activity_customer_idx')],
            },
        ),
    ]
