# Generated by Django 5.2.17 on 2026-09-06 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_crmactivity_enquiry'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmactivity',
            name='service_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='service.serviceticket'),
        ),
    ]
