# Generated by Django 5.2.17 on 2026-08-11 16:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('crm', '0003_crmactivity_enquiry'),
        ('documents', '0001_initial'),
        ('enquiries', '0003_alter_enquiry_status'),
        ('estimation', '0001_initial'),
        ('masters', '0002_india_defaults'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_number', models.CharField(max_length=80)),
                ('path', models.CharField(choices=[('STANDARD', 'Standard quotation'), ('QUICK', 'Quick quotation')], max_length=20)),
                ('quick_reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_APPROVAL', 'In approval'), ('APPROVED', 'Approved'), ('READY_TO_SEND', 'Ready to send'), ('SENT', 'Sent'), ('UNDER_NEGOTIATION', 'Under negotiation'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('READY_FOR_SALES_ORDER', 'Ready for Sales Order')], default='DRAFT', max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='organization.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='crm.customer')),
                ('customer_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='crm.customercontact')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='enquiries.enquiry')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='estimation.commercialestimate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_quotations', to='organization.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('revision_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_APPROVAL', 'In approval'), ('APPROVED', 'Approved'), ('READY_TO_SEND', 'Ready to send'), ('SENT', 'Sent'), ('SUPERSEDED', 'Superseded'), ('RETURNED', 'Returned for changes'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('introduction', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('inclusions', models.TextField(blank=True)),
                ('exclusions', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('payment_terms', models.TextField(blank=True)),
                ('delivery_terms', models.TextField(blank=True)),
                ('warranty_terms', models.TextField(blank=True)),
                ('freight_terms', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('estimate_snapshot', models.JSONField(blank=True, default=dict)),
                ('commercial_snapshot', models.JSONField(blank=True, default=dict)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_reason', models.CharField(blank=True, max_length=250)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('approval_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_revision', to='approvals.approvalrequest')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotation_revisions', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_revisions', to='masters.currency')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='quotations.quotation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_quotation_revisions', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='quotations.quotationrevision')),
            ],
            options={
                'ordering': ['quotation', '-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='QuotationNegotiation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.CharField(choices=[('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PRINT', 'Print / hand delivery'), ('IN_PERSON', 'In person'), ('OTHER', 'Other')], max_length=20)),
                ('summary', models.TextField()),
                ('customer_request', models.TextField(blank=True)),
                ('our_response', models.TextField(blank=True)),
                ('commercial_impact', models.TextField(blank=True)),
                ('material_change', models.BooleanField(default=False)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_negotiations', to=settings.AUTH_USER_MODEL)),
                ('follow_up_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_negotiations', to='organization.employee')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negotiations', to='quotations.quotation')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negotiations', to='quotations.quotationrevision')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField()),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_of_measure', models.CharField(default='NOS', max_length=40)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('tax_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('is_optional', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='quotations.quotationrevision')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='QuotationCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PRINT', 'Print / hand delivery'), ('IN_PERSON', 'In person'), ('OTHER', 'Other')], max_length=20)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Sent to customer'), ('INBOUND', 'Received from customer')], max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField()),
                ('manual_reference', models.CharField(blank=True, max_length=250)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_communications', to='crm.customercontact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_communications', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='quotations.quotationrevision')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_quotations', to='quotations.quotationrevision'),
        ),
        migrations.CreateModel(
            name='CustomerCommercialConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('VERBAL', 'Verbal confirmation'), ('WHATSAPP', 'WhatsApp confirmation'), ('EMAIL', 'Email confirmation'), ('PURCHASE_ORDER', 'Purchase order')], max_length=30)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmation_reference', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('po_pending', models.BooleanField(default=False)),
                ('po_number', models.CharField(blank=True, max_length=120)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('ready_for_sales_order_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_quotations', to=settings.AUTH_USER_MODEL)),
                ('po_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_confirmations', to='documents.document')),
                ('ready_for_sales_order_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_ready_confirmations', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_confirmation', to='quotations.quotation')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_confirmations', to='quotations.quotationrevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_templates', to='organization.company')),
                ('output_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_templates', to='documents.documentcategory')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_templates', to='documents.document')),
            ],
            options={
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuotationGeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('COMPLETE', 'Word and PDF available'), ('WORD_ONLY', 'Word available; PDF failed')], max_length=20)),
                ('context_snapshot', models.JSONField(default=dict)),
                ('pdf_error', models.CharField(blank=True, max_length=500)),
                ('docx_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_quotation_docx', to='documents.document')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_quotation_documents', to=settings.AUTH_USER_MODEL)),
                ('pdf_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_quotation_pdf', to='documents.document')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='quotations.quotationrevision')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='quotations.quotationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationTextTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=180)),
                ('section', models.CharField(choices=[('INTRODUCTION', 'Introduction'), ('SCOPE', 'Scope'), ('INCLUSIONS', 'Inclusions'), ('EXCLUSIONS', 'Exclusions'), ('ASSUMPTIONS', 'Assumptions'), ('PAYMENT', 'Payment terms'), ('DELIVERY', 'Delivery terms'), ('WARRANTY', 'Warranty terms'), ('FREIGHT', 'Freight terms')], max_length=30)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_text_templates', to='organization.company')),
            ],
            options={
                'ordering': ['company', 'section', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='quotationrevision',
            constraint=models.UniqueConstraint(fields=('quotation', 'revision_number'), name='unique_quotation_revision'),
        ),
        migrations.AddConstraint(
            model_name='quotationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gt', 0)), name='positive_quotation_revision'),
        ),
        migrations.AddConstraint(
            model_name='quotationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='nonnegative_quotation_total'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.UniqueConstraint(fields=('revision', 'line_number'), name='unique_quotation_line'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(('line_number__gt', 0)), name='positive_quote_line'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='positive_quote_quantity'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['company', 'status', '-updated_at'], name='quotation_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['customer', '-created_at'], name='quotation_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['owner', 'status'], name='quotation_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('company', 'quotation_number'), name='unique_company_quotation_number'),
        ),
        migrations.AddConstraint(
            model_name='quotationtemplate',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_quotation_template_code'),
        ),
        migrations.AddConstraint(
            model_name='quotationtexttemplate',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_quote_text_template_code'),
        ),
    ]
