# Generated by Django 5.2.17 on 2026-08-11 11:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_crmactivity_enquiry'),
        ('documents', '0001_initial'),
        ('enquiries', '0002_enquiry_cancellation_reason'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('integration_type', models.CharField(choices=[('WEBSITE', 'Website')], max_length=30)),
                ('key_id', models.CharField(max_length=100, unique=True)),
                ('secret_hash', models.CharField(max_length=64)),
                ('allowed_source', models.CharField(blank=True, max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_credentials', to='organization.company')),
            ],
            options={
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalEnquirySubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('WEBSITE', 'Website')], default='WEBSITE', max_length=30)),
                ('source_type', models.CharField(choices=[('CONTACT_FORM', 'Contact form'), ('PRODUCT_QUOTE', 'Product request quote'), ('CAMPAIGN', 'Campaign form')], max_length=30)),
                ('external_submission_id', models.CharField(max_length=160)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('request_id', models.CharField(max_length=160)),
                ('payload_checksum', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('person_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('normalized_phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('product_reference', models.CharField(blank=True, max_length=160)),
                ('product_name', models.CharField(blank=True, max_length=250)),
                ('product_url', models.URLField(blank=True)),
                ('source_page_url', models.URLField(blank=True)),
                ('referrer_url', models.URLField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=160)),
                ('utm_medium', models.CharField(blank=True, max_length=160)),
                ('utm_campaign', models.CharField(blank=True, max_length=160)),
                ('utm_term', models.CharField(blank=True, max_length=160)),
                ('utm_content', models.CharField(blank=True, max_length=160)),
                ('remote_ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('spam_status', models.CharField(choices=[('UNKNOWN', 'Not screened'), ('LIKELY_VALID', 'Likely valid'), ('SUSPICIOUS', 'Suspicious'), ('SPAM', 'Spam')], default='UNKNOWN', max_length=30)),
                ('spam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('review_status', models.CharField(choices=[('NEW', 'New'), ('NEEDS_REVIEW', 'Needs review'), ('POSSIBLE_DUPLICATE', 'Possible duplicate'), ('ACCEPTED', 'Accepted'), ('CONVERTED', 'Converted'), ('REJECTED', 'Rejected'), ('SPAM', 'Spam')], default='NEW', max_length=30)),
                ('duplicate_status', models.CharField(choices=[('NONE', 'No likely duplicate'), ('POSSIBLE', 'Possible duplicate'), ('REVIEWED', 'Reviewed')], default='NONE', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_external_enquiries', to='organization.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_enquiries', to='organization.company')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_external_enquiries', to=settings.AUTH_USER_MODEL)),
                ('converted_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_external_enquiries', to='crm.customercontact')),
                ('converted_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_external_enquiries', to='crm.customer')),
                ('converted_enquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_submission', to='enquiries.enquiry')),
                ('matched_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matched_external_enquiries', to='crm.customercontact')),
                ('matched_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matched_external_enquiries', to='crm.customer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_external_enquiries', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='external_enquiries.integrationcredential')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalEnquiryAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('safe_display_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('mime_type', models.CharField(max_length=120)),
                ('extension', models.CharField(max_length=20)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('validation_status', models.CharField(choices=[('ACCEPTED', 'Validated'), ('REJECTED', 'Rejected')], default='ACCEPTED', max_length=20)),
                ('scan_status', models.CharField(choices=[('NOT_SCANNED', 'Not scanned'), ('PENDING', 'Pending scan'), ('CLEAN', 'Clean'), ('QUARANTINED', 'Quarantined'), ('FAILED', 'Scan failed')], default='NOT_SCANNED', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_attachment', to='documents.document')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='external_enquiries.externalenquirysubmission')),
            ],
            options={
                'ordering': ['uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('submission', 'checksum_sha256'), name='unique_external_attachment_checksum')],
            },
        ),
        migrations.AddIndex(
            model_name='integrationcredential',
            index=models.Index(fields=['company', 'integration_type', 'is_active'], name='integration_active_idx'),
        ),
        migrations.AddIndex(
            model_name='externalenquirysubmission',
            index=models.Index(fields=['company', 'review_status', '-received_at'], name='external_review_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='externalenquirysubmission',
            index=models.Index(fields=['company', 'email'], name='external_email_idx'),
        ),
        migrations.AddIndex(
            model_name='externalenquirysubmission',
            index=models.Index(fields=['company', 'normalized_phone'], name='external_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='externalenquirysubmission',
            index=models.Index(fields=['external_submission_id'], name='external_submission_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalenquirysubmission',
            constraint=models.UniqueConstraint(fields=('company', 'channel', 'external_submission_id'), name='unique_external_submission'),
        ),
        migrations.AddConstraint(
            model_name='externalenquirysubmission',
            constraint=models.UniqueConstraint(fields=('credential', 'idempotency_key'), name='unique_external_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='externalenquirysubmission',
            constraint=models.UniqueConstraint(fields=('credential', 'request_id'), name='unique_external_request'),
        ),
        migrations.AddConstraint(
            model_name='externalenquirysubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('converted_enquiry__isnull', False), ('review_status', 'CONVERTED')), models.Q(('converted_enquiry__isnull', True), models.Q(('review_status', 'CONVERTED'), _negated=True)), _connector='OR'), name='converted_submission_has_enquiry'),
        ),
    ]
