# Generated by Django 5.2.17 on 2026-08-18 18:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('crm', '0003_crmactivity_enquiry'),
        ('documents', '0001_initial'),
        ('enquiries', '0003_alter_enquiry_status'),
        ('masters', '0002_india_defaults'),
        ('organization', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DIFFERENCE_REVIEW', 'Differences Need Review'), ('ACCEPTED_WITH_DIFFERENCES', 'Accepted with Differences'), ('SUPERSEDED', 'Superseded'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_purchase_orders', to='organization.company')),
                ('confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_purchase_orders', to='quotations.customercommercialconfirmation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='crm.customer')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_purchase_orders', to='quotations.quotation')),
                ('responsible_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_customer_purchase_orders', to='organization.employee')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPurchaseOrderRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('revision_number', models.PositiveIntegerField()),
                ('customer_revision_reference', models.CharField(blank=True, max_length=120)),
                ('po_date', models.DateField()),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('stated_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tax_information', models.JSONField(blank=True, default=dict)),
                ('line_snapshot', models.JSONField(blank=True, default=list)),
                ('delivery_information', models.TextField(blank=True)),
                ('payment_terms', models.TextField(blank=True)),
                ('warranty_terms', models.TextField(blank=True)),
                ('customer_reference', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('match_status', models.CharField(choices=[('NOT_REVIEWED', 'Not Reviewed'), ('MATCHES', 'Matches Quotation'), ('DIFFERENCES', 'Differences Need Review'), ('ACCEPTED_DIFFERENCES', 'Accepted with Differences')], default='NOT_REVIEWED', max_length=32)),
                ('variance_snapshot', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_po_revisions', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_po_revisions', to='masters.currency')),
                ('customer_purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='sales.customerpurchaseorder')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='sales.customerpurchaseorderrevision')),
                ('supporting_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_po_revisions', to='documents.document')),
            ],
            options={
                'ordering': ['customer_purchase_order', '-revision_number'],
            },
        ),
        migrations.AddField(
            model_name='customerpurchaseorder',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_purchase_orders', to='sales.customerpurchaseorderrevision'),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.CharField(max_length=12)),
                ('sales_order_number', models.CharField(max_length=80)),
                ('order_mode', models.CharField(choices=[('QUOTATION_BASED', 'Quotation Based'), ('DIRECT', 'Direct Sales Order')], max_length=24)),
                ('project_required', models.BooleanField(default=True)),
                ('po_pending', models.BooleanField(default=False)),
                ('direct_reason', models.CharField(blank=True, max_length=80)),
                ('direct_reason_notes', models.TextField(blank=True)),
                ('confirmation_channel', models.CharField(blank=True, max_length=40)),
                ('confirmation_reference', models.CharField(blank=True, max_length=250)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Waiting for Approval'), ('APPROVED', 'Approved'), ('RELEASED', 'Released for Execution'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled'), ('SUPERSEDED', 'Replaced by New Revision')], default='DRAFT', max_length=28)),
                ('accepted_quotation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order', to='quotations.quotation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='organization.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='crm.customercontact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='crm.customer')),
                ('customer_confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='quotations.customercommercialconfirmation')),
                ('customer_purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='sales.customerpurchaseorder')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='enquiries.enquiry')),
                ('responsible_sales_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_sales_orders', to='organization.employee')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='crm.customersite')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_version', models.PositiveIntegerField(default=1)),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Waiting for Approval'), ('APPROVED', 'Approved'), ('RELEASED', 'Released for Execution'), ('RETURNED', 'Returned for Changes'), ('SUPERSEDED', 'Replaced by New Revision'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=28)),
                ('customer_reference', models.CharField(blank=True, max_length=250)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('requested_delivery', models.DateField(blank=True, null=True)),
                ('promised_delivery', models.DateField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True)),
                ('delivery_terms', models.TextField(blank=True)),
                ('warranty_terms', models.TextField(blank=True)),
                ('freight_terms', models.TextField(blank=True)),
                ('installation_terms', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('exclusions', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('commercial_snapshot', models.JSONField(blank=True, default=dict)),
                ('po_snapshot', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('revision_reason', models.CharField(blank=True, max_length=500)),
                ('approval_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_revision', to='approvals.approvalrequest')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sales_order_revisions', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_revisions', to='masters.currency')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_sales_order_revisions', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_sales_order_revisions', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='sales.salesorder')),
                ('source_customer_po_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_revisions', to='sales.customerpurchaseorderrevision')),
                ('source_quotation_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_revisions', to='quotations.quotationrevision')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='sales.salesorderrevision')),
            ],
            options={
                'ordering': ['sales_order', '-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField()),
                ('quotation_line_id', models.UUIDField(blank=True, null=True)),
                ('customer_po_line_reference', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(max_length=1000)),
                ('long_description', models.TextField(blank=True)),
                ('customer_item_reference', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_of_measure', models.CharField(default='NOS', max_length=40)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('tax_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('promised_delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_text', models.CharField(blank=True, max_length=250)),
                ('customer_visible_note', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('project_scope_category', models.CharField(blank=True, max_length=120)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.salesorderrevision')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_sales_orders', to='sales.salesorderrevision'),
        ),
        migrations.AddConstraint(
            model_name='customerpurchaseorderrevision',
            constraint=models.UniqueConstraint(fields=('customer_purchase_order', 'revision_number'), name='unique_customer_po_revision'),
        ),
        migrations.AddConstraint(
            model_name='customerpurchaseorderrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gt', 0)), name='positive_customer_po_revision'),
        ),
        migrations.AddConstraint(
            model_name='customerpurchaseorderrevision',
            constraint=models.CheckConstraint(condition=models.Q(('stated_total__isnull', True), ('stated_total__gte', 0), _connector='OR'), name='nonnegative_customer_po_total'),
        ),
        migrations.AddIndex(
            model_name='customerpurchaseorder',
            index=models.Index(fields=['company', 'status', '-updated_at'], name='customer_po_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpurchaseorder',
            index=models.Index(fields=['customer', 'po_number'], name='customer_po_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerpurchaseorder',
            constraint=models.UniqueConstraint(fields=('company', 'customer', 'po_number'), name='unique_customer_po_number'),
        ),
        migrations.AddConstraint(
            model_name='salesorderrevision',
            constraint=models.UniqueConstraint(fields=('sales_order', 'revision_number'), name='unique_sales_order_revision'),
        ),
        migrations.AddConstraint(
            model_name='salesorderrevision',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='nonnegative_sales_order_total'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.UniqueConstraint(fields=('revision', 'line_number'), name='unique_sales_order_line'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('line_number__gt', 0)), name='positive_sales_order_line'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='positive_sales_order_quantity'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['company', 'status', '-updated_at'], name='sales_order_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer', '-created_at'], name='sales_order_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['responsible_sales_employee', 'status'], name='sales_order_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('company', 'sales_order_number'), name='unique_company_sales_order_number'),
        ),
    ]
