# Generated by Django 5.2.17 on 2026-08-10 21:02

import decimal
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_crmactivity'),
        ('masters', '0002_india_defaults'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry_number', models.CharField(max_length=80)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('customer_reference', models.CharField(blank=True, max_length=160)),
                ('subject', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under review'), ('ENGINEERING_REVIEW', 'Engineering review'), ('ESTIMATION', 'Estimation'), ('QUOTATION_PREPARATION', 'Quotation preparation'), ('QUOTATION_SENT', 'Quotation sent'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('lost_reason', models.CharField(blank=True, max_length=500)),
                ('competitor', models.CharField(blank=True, max_length=250)),
                ('customer_feedback', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_enquiries', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='organization.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enquiries', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='masters.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='crm.customer')),
                ('customer_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='crm.customercontact')),
                ('customer_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='crm.customersite')),
                ('responsible_salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_enquiries', to='organization.employee')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('customer_reference', models.CharField(blank=True, max_length=160)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.0001'))])),
                ('technical_specification', models.TextField(blank=True)),
                ('requested_delivery', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='enquiries.enquiry')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_items', to='masters.unitofmeasure')),
            ],
            options={
                'ordering': ['enquiry', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('COMMERCIAL', 'Commercial'), ('DELIVERY', 'Delivery'), ('COMPLIANCE', 'Compliance'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('customer_specification_reference', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='enquiries.enquiry')),
            ],
            options={
                'ordering': ['enquiry', 'requirement_type', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['company', 'status', '-received_date'], name='enquiry_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['customer', 'status'], name='enquiry_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['responsible_salesperson', 'status'], name='enquiry_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['company', 'due_date'], name='enquiry_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.UniqueConstraint(fields=('company', 'enquiry_number'), name='unique_company_enquiry_number'),
        ),
        migrations.AddIndex(
            model_name='enquiryitem',
            index=models.Index(fields=['enquiry', 'line_number'], name='enquiry_item_line_idx'),
        ),
        migrations.AddConstraint(
            model_name='enquiryitem',
            constraint=models.UniqueConstraint(fields=('enquiry', 'line_number'), name='unique_enquiry_item_line'),
        ),
        migrations.AddConstraint(
            model_name='enquiryitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_number__gt', 0)), name='positive_enquiry_item_line'),
        ),
        migrations.AddIndex(
            model_name='enquiryrequirement',
            index=models.Index(fields=['enquiry', 'requirement_type'], name='enquiry_requirement_idx'),
        ),
    ]
