# Generated by Django 5.2.17 on 2026-08-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
