# Generated by Django 5.2.17 on 2026-08-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_enquiry_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under review'), ('ENGINEERING_REVIEW', 'Engineering review'), ('ESTIMATION', 'Estimation'), ('ESTIMATION_COMPLETE', 'Estimation complete'), ('QUOTATION_PREPARATION', 'Quotation preparation'), ('QUOTATION_SENT', 'Quotation sent'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
    ]
